config/routes.rb
Rails.application.routes.draw do




  ActiveAdmin.routes(self)
  resources :specific_items
  get 'cookies_test/set_cookies'
  get 'cookies_test/show_cookies'
  get 'cookies_test/delete_cookies'
  resources :articles
  resources :orders
  resources :order_line_items
  devise_for :users
  resources :users
  resources :inventory_items
  resources :inventory_models
  resources :inventory_item_categories
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get '/home' => 'static_pages#home'
  get '/help' => 'static_pages#help'
  get '/about_us' => 'static_pages#about_us'
  get '/contact' => 'static_pages#contact'
  get '/shopping_cart' => 'static_pages#shopping_cart'
  get '/categories' => 'inventory_item_categories#index'
  get '/checkout' => 'static_pages#checkout'
  #get '/articles' => 'static_pages#articles'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'static_pages#home'
end

app/models/inventory_model.rb
class InventoryModel < ApplicationRecord
	has_many :inventory_items
  mount_uploader :image, ImageUploader  # carrierwave support for our image column
  serialize :image, JSON # If you use SQLite, add this line.  

  def add_inventory_item_to_model(inventory_item)    
    inventory_item.inventory_model.increment(:quantity)
  end

end

app/controllers/inventory_models_controller.rb
class InventoryModelsController < ApplicationController
  before_action :set_inventory_model, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]  
  # GET /inventory_models
  # GET /inventory_models.json
  def index
    @inventory_models = InventoryModel.all
  end

  # GET /inventory_models/1
  # GET /inventory_models/1.json
  def show
  end

  # GET /inventory_models/new
  def new
    @inventory_model = InventoryModel.new
  end

  # GET /inventory_models/1/edit
  def edit
  end

  # POST /inventory_models
  # POST /inventory_models.json
  def create
    @inventory_model = InventoryModel.new(inventory_model_params)

    respond_to do |format|
      if @inventory_model.save
        format.html { redirect_to @inventory_model, notice: 'Inventory model was successfully created.' }
        format.json { render :show, status: :created, location: @inventory_model }
      else
        format.html { render :new }
        format.json { render json: @inventory_model.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /inventory_models/1
  # PATCH/PUT /inventory_models/1.json
  def update
    respond_to do |format|
      if @inventory_model.update(inventory_model_params)
        format.html { redirect_to @inventory_model, notice: 'Inventory model was successfully updated.' }
        format.json { render :show, status: :ok, location: @inventory_model }
      else
        format.html { render :edit }
        format.json { render json: @inventory_model.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /inventory_models/1
  # DELETE /inventory_models/1.json
  def destroy
    @inventory_model.destroy
    respond_to do |format|
      format.html { redirect_to inventory_models_url, notice: 'Inventory model was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_inventory_model
      @inventory_model = InventoryModel.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def inventory_model_params
      params.require(:inventory_model).permit(:inventory_model_name, :quantity, :image, :sold_quantity)
    end
end

app/helpers/inventory_models_helper.rb
module InventoryModelsHelper
  def abc
  	binding.pry
  end	
end

app/views/inventory_models/_form.html.erb
<%= form_with(model: inventory_model, local: true) do |form| %>
  <% if inventory_model.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(inventory_model.errors.count, "error") %> prohibited this inventory_model from being saved:</h2>

      <ul>
      <% inventory_model.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :inventory_model_name %>
    <%= form.text_field :inventory_model_name %>
  </div>

  <div class="field">
    <%= form.label :quantity %>
    <%= form.number_field :quantity %>
  </div>

  <div class="field">
    <%= form.label :sold_quantity %>
    <%= form.number_field :sold_quantity %>
  </div>

  <div class="field">
    <%= form.label :image %>
    <%= form.file_field  :image %>
  </div>
  
  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/inventory_models/edit.html.erb
<h1>Editing Inventory Model</h1>

<%= render 'form', inventory_model: @inventory_model %>

<%= link_to 'Show', @inventory_model %> |
<%= link_to 'Back', inventory_models_path %>

app/views/inventory_models/index.html.haml
- if user_signed_in? && current_user.admin
  %p#notice= notice
  %h1 Inventory Models
  %table
    %thead
      %tr
        %th Model name
        %th Quantity
        %th Sold Quantity
        %th image
        %th(colspan="3")
    %tbody
      - @inventory_models.each do |inventory_model|
        %tr
          %td= inventory_model.inventory_model_name
          %td= inventory_model.quantity
          %td= inventory_model.sold_quantity
          %td= inventory_model.image          
          %td= link_to 'Show', inventory_model
          %td= link_to 'Edit', edit_inventory_model_path(inventory_model)
          %td= link_to 'Destroy', inventory_model, method: :delete, data: { confirm: 'Are you sure?' }
  %br/
  = link_to 'New Inventory Model', new_inventory_model_path 
- else
  .card(style = "margin: 20px 0px;")
    .card-header
      Featured Products
      //= will_paginate @clients, renderer: WillPaginate::ActionView::BootstrapLinkRenderer
    .card-body
      .row
        - @inventory_models.each do |inventory_model| 
          .card.text-center.col-lg-4.col-md-6(style = "margin: 5px 0px;")          
            //- binding.pru
            = link_to image_tag(inventory_model.image_url(:inventory_item)), inventory_model, :class => "img card-img-top"          
            .card-body       
              %h5.card-title 
                =inventory_model.inventory_model_name
              %p.card-text
                Quantity:
                =inventory_model.quantity
              %p.card-text
                Sold:
                =inventory_model.sold_quantity  
            = link_to "Details", inventory_model, :class => "a btn btn-primary"

app/views/inventory_models/new.html.erb
<h1>New Inventory Model</h1>

<%= render 'form', inventory_model: @inventory_model %>

<%= link_to 'Back', inventory_models_path %>

app/views/inventory_models/show.html.haml
- if user_signed_in? && current_user.admin
  %p#notice= notice
  %p
    %strong Model name:
    = @inventory_model.inventory_model_name
  %p
    %strong Quantity:
    = @inventory_model.quantity
  %p
    %strong Quantity:
    = @inventory_model.sold_quantity  
  = link_to 'Edit', edit_inventory_model_path(@inventory_model)
  |
  = link_to 'Back', inventory_models_path
- else
  .card(style = "margin: 20px 0px;")
    .card-header
      %strong 
        Model name:  
        = @inventory_model.inventory_model_name
        - @inventory_items = @inventory_model.inventory_items
    .card-body
      .row        

        - @inventory_items.each do |inventory_item|
          .card.text-center.col-lg-4.col-md-6(style = "margin: 5px 0px;")          
            = link_to image_tag(inventory_item.image_url(:inventory_item)), inventory_item, :class => "img card-img-top"
            .card-body       
              %h5.card-title 
                =inventory_item.name
              %p.card-text
                Unit Price:
                =number_to_currency inventory_item.price 
              = button_to 'Add to cart', order_line_items_path(inventory_item_id: inventory_item), class: 'btn button btn-primary'