config/routes.rb
Rails.application.routes.draw do




  ActiveAdmin.routes(self)
  resources :specific_items
  get 'cookies_test/set_cookies'
  get 'cookies_test/show_cookies'
  get 'cookies_test/delete_cookies'
  resources :articles
  resources :orders
  resources :order_line_items
  devise_for :users
  resources :users
  resources :inventory_items
  resources :inventory_models
  resources :inventory_item_categories
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get '/home' => 'static_pages#home'
  get '/help' => 'static_pages#help'
  get '/about_us' => 'static_pages#about_us'
  get '/contact' => 'static_pages#contact'
  get '/shopping_cart' => 'static_pages#shopping_cart'
  get '/categories' => 'inventory_item_categories#index'
  get '/checkout' => 'static_pages#checkout'
  #get '/articles' => 'static_pages#articles'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'static_pages#home'
end

app/models/specific_item.rb
class SpecificItem < ApplicationRecord
  belongs_to :inventory_item
  
end

app/controllers/specific_items_controller.rb
class SpecificItemsController < ApplicationController
  before_action :set_specific_item, only: [:show, :edit, :update, :destroy]
  #after_action :increase_inventory_item
  before_action :authenticate_user!
  before_action do 
  redirect_to new_user_session_path unless current_user && current_user.admin?
  end
  def index
    @grid = SpecificItemsGrid.new(grid_params) do |scope|
      scope.page(params[:page])
    end
  end

  def show

  end

  # GET /specific_items/new
  def new
    @specific_item = SpecificItem.new
  end

  # GET /specific_items/1/edit
  def edit

  end

  # POST /specific_items
  # POST /specific_items.json
  def create
    @specific_item = SpecificItem.new(specific_item_params)

    respond_to do |format|
      if @specific_item.save
        format.html { redirect_to @specific_item, notice: 'Specific item was successfully created.' }
        format.json { render :show, status: :created, location: @specific_item }
      else
        format.html { render :new }
        format.json { render json: @specific_item.errors, status: :unprocessable_entity }
      end      
    end    
    increase_inventory_item(@specific_item)
    #binding.pry
  end

  # PATCH/PUT /specific_items/1
  # PATCH/PUT /specific_items/1.json
  def update
    respond_to do |format|
      if @specific_item.update(specific_item_params)
        format.html { redirect_to @specific_item, notice: 'Specific item was successfully updated.' }
        format.json { render :show, status: :ok, location: @specific_item }
      else
        format.html { render :edit }
        format.json { render json: @specific_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /specific_items/1
  # DELETE /specific_items/1.json
  def destroy
    @specific_item.destroy
    respond_to do |format|
      format.html { redirect_to specific_items_url, notice: 'Specific item was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

private

  def grid_params
    params.fetch(:specific_items_grid, {}).permit!
  end
  #before_action :authenticate_admin!  
  # GET /specific_items
  # GET /specific_items.json

  # GET /specific_items/1
  # GET /specific_items/1.json


    # Use callbacks to share common setup or constraints between actions.
    def set_specific_item
      @specific_item = SpecificItem.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def specific_item_params
      params.require(:specific_item).permit(:inventory_item_id, :serial_number)
    end

    def increase_inventory_item(specific_item)
      inventory_item = InventoryItem.find(specific_item.inventory_item_id.to_s)
      inventory_item.increment(:quantity)
      inventory_item.save
      #binding.pry
    end
end

app/helpers/specific_items_helper.rb
module SpecificItemsHelper
end

app/views/specific_items/_form.html.slim
= simple_form_for(@specific_item) do |f|
  = f.error_notification
  = f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present?

  .form-inputs
    = f.association :inventory_item
    = f.input :serial_number

  .form-actions
    = f.button :submit

app/views/specific_items/edit.html.slim
h1 Editing specific_item

== render 'form'

=> link_to 'Show', @specific_item
'|
=< link_to 'Back', specific_items_path

app/views/specific_items/index.html.erb
<%= datagrid_form_for @grid, :method => :get, :url => specific_items_path %>

<%= paginate(@grid.assets) %>
<%= datagrid_table @grid %>
<%= paginate(@grid.assets) %>

app/views/specific_items/index.html.slim
h1 Listing specific_items

table
  thead
    tr
      th Inventory item.name
      th Serial number
      th
      th
      th

  tbody
    - @specific_items.each do |specific_item|
      tr
        td = specific_item.inventory_item.name
        td = specific_item.serial_number
        td = link_to 'Show', specific_item
        td = link_to 'Edit', edit_specific_item_path(specific_item)
        td = link_to 'Destroy', specific_item, data: { confirm: 'Are you sure?' }, method: :delete

br

= link_to 'New Specific item', new_specific_item_path

app/views/specific_items/new.html.slim
h1 New specific_item

== render 'form'

= link_to 'Back', specific_items_path

app/views/specific_items/show.html.slim
p#notice = notice

p
  strong Inventory item:
  = @specific_item.inventory_item
p
  strong Inventory item:
  = @specific_item.inventory_item_id
p
  strong Serial number:
  = @specific_item.serial_number

=> link_to 'Edit', edit_specific_item_path(@specific_item)
'|
=< link_to 'Back', specific_items_path