config/routes.rb
Rails.application.routes.draw do




  ActiveAdmin.routes(self)
  resources :specific_items
  get 'cookies_test/set_cookies'
  get 'cookies_test/show_cookies'
  get 'cookies_test/delete_cookies'
  resources :articles
  resources :orders
  resources :order_line_items
  devise_for :users
  resources :users
  resources :inventory_items
  resources :inventory_models
  resources :inventory_item_categories
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get '/home' => 'static_pages#home'
  get '/help' => 'static_pages#help'
  get '/about_us' => 'static_pages#about_us'
  get '/contact' => 'static_pages#contact'
  get '/shopping_cart' => 'static_pages#shopping_cart'
  get '/categories' => 'inventory_item_categories#index'
  get '/checkout' => 'static_pages#checkout'
  #get '/articles' => 'static_pages#articles'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'static_pages#home'
end

app/models/inventory_item.rb
class InventoryItem < ApplicationRecord
  before_destroy :not_refereced_by_any_line_item
  belongs_to :user, optional: true
  belongs_to :inventory_item_categories, required: false
  belongs_to :inventory_models, required: false
  has_many :order_line_items
  has_many :specific_item
  mount_uploader :image, ImageUploader  # carrierwave support for our image column
  serialize :image, JSON # If you use SQLite, add this line.  

  #mount_uploader :image, ImageUploader
  #serialize :image, JSON # If you use SQLite, add this line

  validates :name, :description, :price, :inventory_model_id, :inventory_item_category_id, :image, presence: true
  #validates :description, length: { maximum: 1000, too_long: "%{count} characters is the maximum aloud. "}
  #validates :title, length: { maximum: 140, too_long: "%{count} characters is the maximum aloud. "}
  #validates :price, length: { maximum: 7 }

  #BRAND = %w{ Fender Gibson Epiphone ESP Martin Dean Taylor Jackson PRS  Ibanez Charvel Washburn }
  #FINISH = %w{ Black White Navy Blue Red Clear Satin Yellow Seafoam }
  #CONDITION = %w{ New Excellent Mint Used Fair Poor }

  private

  def not_refereced_by_any_line_item
    unless order_line_items.empty?
      errors.add(:base, "Line items present")
      throw :abort
    end
  end

end

app/controllers/inventory_items_controller.rb
class InventoryItemsController < ApplicationController
  before_action :set_inventory_item, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]  
  #after_action:increment_model_quantity
  include InventoryModelsHelper

  # GET /inventory_items
  # GET /inventory_items.json
  def index
    @inventory_items = InventoryItem.all.order("created_at desc")
  end

  # GET /inventory_items/1
  # GET /inventory_items/1.json
  def show
    
  end

  # GET /inventory_items/new
  def new
    @inventory_item = InventoryItem.new
  end

  # GET /inventory_items/1/edit
  def edit
  end

  # POST /inventory_items
  # POST /inventory_items.json
  def create    
    @inventory_item = InventoryItem.new(inventory_item_params)
    
    
    respond_to do |format|
      if @inventory_item.save
        format.html { redirect_to @inventory_item, notice: 'Inventory item was successfully created.' }
        format.js
        format.json { render :show, status: :created, location: @inventory_item }
        @related_model = InventoryModel.find_by(inventory_item_params["inventory_model_id"])

        @related_model.increment(:quantity)

        @related_model.save
      else
        format.html { render :new }
        format.json { render json: @inventory_item.errors, status: :unprocessable_entity }
      end  
      #binding.pry
    end
    #@inventory_item.inventory_model.increment(:quantity)
    
  end

  # PATCH/PUT /inventory_items/1
  # PATCH/PUT /inventory_items/1.json
  def update
    respond_to do |format|
      if @inventory_item.update(inventory_item_params)
        format.html { redirect_to @inventory_item, notice: 'Inventory item was successfully updated.' }
        format.json { render :show, status: :ok, location: @inventory_item }
      else
        format.html { render :edit }
        format.json { render json: @inventory_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /inventory_items/1
  # DELETE /inventory_items/1.json
  def destroy
    @inventory_item.destroy
    respond_to do |format|
      format.html { redirect_to inventory_items_url, notice: 'Inventory item was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_inventory_item
      @inventory_item = InventoryItem.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def inventory_item_params
      params.require(:inventory_item).permit(:name, :price, :description, :warehoused_on, :inventory_item_category_id, :inventory_model_id, :image)
    end
end

app/helpers/inventory_items_helper.rb
module InventoryItemsHelper
end

app/views/inventory_items/_form.html.erb
<%= form_for @inventory_item do |form| %>
  <% if inventory_item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(inventory_item.errors.count, "error") %> prohibited this inventory_item from being saved:</h2>

      <ul>
      <% inventory_item.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :price %>
    <%= form.text_field :price %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="field">
    <%= form.label :warehoused_on %>
    <%= form.date_select :warehoused_on %>
  </div>

  <div class="field">
    <%= form.label :inventory_item_category_id %>
    <%= form.number_field :inventory_item_category_id %>
  </div>

  <div class="field">
    <%= form.label :inventory_model_id %>
    <%= form.number_field :inventory_model_id %>
  </div>

  <div class="field">
    <%= form.label :image %>
    <%= form.file_field  :image %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/inventory_items/edit.html.erb
<h1>Editing Inventory Item</h1>

<%= render 'form', inventory_item: @inventory_item %>

<%= link_to 'Show', @inventory_item %> |
<%= link_to 'Back', inventory_items_path %>

app/views/inventory_items/index.html.haml
- if user_signed_in? && current_user.admin
  %p#notice= notice
  %h1 Inventory Items
  %table
    %thead
      %tr
        %th Inv item category
        %th Model
        %th Name
        %th Price
        %th Description
        %th Warehoused on
        %th(colspan="3")
    %tbody
      - @inventory_items.each do |inventory_item|
        %tr
          %td= inventory_item.inventory_item_category_id
          %td= inventory_item.inventory_model_id
          %td= inventory_item.name
          %td= inventory_item.price
          %td= inventory_item.description
          %td= inventory_item.warehoused_on
          %td= link_to 'Show', inventory_item
          %td= link_to 'Edit', edit_inventory_item_path(inventory_item)
          %td= link_to 'Destroy', inventory_item, method: :delete, data: { confirm: 'Are you sure?' }
  %br/
  = link_to 'New Inventory Item', new_inventory_item_path
-else
  = link_to home_path

app/views/inventory_items/new.html.erb
<h1>New Inventory Item</h1>

<%= render 'form', inventory_item: @inventory_item %>

<%= link_to 'Back', inventory_items_path %>

app/views/inventory_items/show.html.haml
- if user_signed_in? && current_user.admin
  %p#notice= notice
  %p
    %strong Inv item category:
    = @inventory_item.inventory_item_category_id
  %p
    %strong Model:
    = @inventory_item.inventory_model_id
  %p
    %strong Name:
    = @inventory_item.name
  %p
    %strong Price:
    = @inventory_item.price
  %p
    %strong Description:
    = @inventory_item.description
  %p
    %strong Warehoused on:
    = @inventory_item.warehoused_on
  %p
    %strong image:
    = @inventory_item.image  
  = link_to 'Edit', edit_inventory_item_path(@inventory_item)
  |
  = link_to 'Back', inventory_items_path
- else           
  .container
    .row
      .col-lg-4
        =link_to image_tag(@inventory_item.image_url(:inventory_item)), @inventory_item, :class => "img card-img-top"
      .col-lg-8
        %dl
          %dd
            %strong Inv item category:
            = @inventory_item.inventory_item_category_id
          %dd
            %strong Model:
            = @inventory_item.inventory_model_id  
          %dd
            %strong Name:
            = @inventory_item.name      
          %dd
            %strong Price:
            = @inventory_item.price
          %dd  
            %strong Description:
            = @inventory_item.description  
          %dd
            .input-group.mb-3
              .input-group
                .input-group
                  = button_to 'Add to cart', order_line_items_path(inventory_item_id: @inventory_item), class: 'btn button btn-primary'        
  .card.text-center(style ="margin-top:10px;")
    .card-header.text-center
      Description
    .card-body
      %h5.card-title 
        =@inventory_item.name
      %p.card-text 
        =@inventory_item.description
      //%a.btn.btn-primary
      //  = link_to 'Details', article
      //= link_to 'Details', @article, :class => "a btn btn-primary"
        