config/routes.rb
Rails.application.routes.draw do




  ActiveAdmin.routes(self)
  resources :specific_items
  get 'cookies_test/set_cookies'
  get 'cookies_test/show_cookies'
  get 'cookies_test/delete_cookies'
  resources :articles
  resources :orders
  resources :order_line_items
  devise_for :users
  resources :users
  resources :inventory_items
  resources :inventory_models
  resources :inventory_item_categories
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get '/home' => 'static_pages#home'
  get '/help' => 'static_pages#help'
  get '/about_us' => 'static_pages#about_us'
  get '/contact' => 'static_pages#contact'
  get '/shopping_cart' => 'static_pages#shopping_cart'
  get '/categories' => 'inventory_item_categories#index'
  get '/checkout' => 'static_pages#checkout'
  #get '/articles' => 'static_pages#articles'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'static_pages#home'
end

app/models/inventory_item_category.rb
class InventoryItemCategory < ApplicationRecord
	has_many :inventory_items
	mount_uploader :image, ImageUploader  # carrierwave support for our image column
  	serialize :image, JSON # If you use SQLite, add this line.  
end

app/controllers/inventory_item_categories_controller.rb
class InventoryItemCategoriesController < ApplicationController
  before_action :set_inventory_item_category, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]  
  # GET /inventory_item_categories
  # GET /inventory_item_categories.json
  def index
    @inventory_item_categories = InventoryItemCategory.all
  end

  # GET /inventory_item_categories/1
  # GET /inventory_item_categories/1.json
  def show
    
  end

  # GET /inventory_item_categories/new
  def new
    @inventory_item_category = InventoryItemCategory.new
  end

  # GET /inventory_item_categories/1/edit
  def edit
  end

  # POST /inventory_item_categories
  # POST /inventory_item_categories.json
  def create
    @inventory_item_category = InventoryItemCategory.new(inventory_item_category_params)

    respond_to do |format|
      if @inventory_item_category.save
        format.html { redirect_to @inventory_item_category, notice: 'Inventory item category was successfully created.' }
        format.json { render :show, status: :created, location: @inventory_item_category }
      else
        format.html { render :new }
        format.json { render json: @inventory_item_category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /inventory_item_categories/1
  # PATCH/PUT /inventory_item_categories/1.json
  def update
    respond_to do |format|
      if @inventory_item_category.update(inventory_item_category_params)
        format.html { redirect_to @inventory_item_category, notice: 'Inventory item category was successfully updated.' }
        format.json { render :show, status: :ok, location: @inventory_item_category }
      else
        format.html { render :edit }
        format.json { render json: @inventory_item_category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /inventory_item_categories/1
  # DELETE /inventory_item_categories/1.json
  def destroy
    @inventory_item_category.destroy
    respond_to do |format|
      format.html { redirect_to inventory_item_categories_url, notice: 'Inventory item category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_inventory_item_category
      @inventory_item_category = InventoryItemCategory.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def inventory_item_category_params
      params.require(:inventory_item_category).permit(:category_name, :image)
    end
end

app/helpers/inventory_item_categories_helper.rb
module InventoryItemCategoriesHelper
end

app/views/inventory_item_categories/_form.html.erb
<%= form_with(model: inventory_item_category, local: true) do |form| %>
  <% if inventory_item_category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(inventory_item_category.errors.count, "error") %> prohibited this inventory_item_category from being saved:</h2>

      <ul>
      <% inventory_item_category.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :category_name %>
    <%= form.text_field :category_name %>
  </div>

  <div class="field">
    <%= form.label :image %>
    <%= form.file_field  :image %>
  </div>
  
  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/inventory_item_categories/edit.html.erb
<h1>Editing Inventory Item Category</h1>

<%= render 'form', inventory_item_category: @inventory_item_category %>

<%= link_to 'Show', @inventory_item_category %> |
<%= link_to 'Back', inventory_item_categories_path %>

app/views/inventory_item_categories/index.html.haml
- if user_signed_in? && current_user.admin
  %p#notice= notice
  %h1 Inventory Item Categories
  %table
    %thead
      %tr
        %th Category name
        %th(colspan="3")
    %tbody
      - @inventory_item_categories.each do |inventory_item_category|
        %tr
          %td= inventory_item_category.category_name
          %td= link_to 'Show', inventory_item_category
          %td= link_to 'Edit', edit_inventory_item_category_path(inventory_item_category)
          %td= link_to 'Destroy', inventory_item_category, method: :delete, data: { confirm: 'Are you sure?' }
  %br/
  = link_to 'New Inventory Item Category', new_inventory_item_category_path
- else
  .card.container(style = "margin: 20px 0px;")
    .card-header
      Featured Products
    .card-body
      .row
        - @inventory_item_categories.each do |inventory_item_category| 
          .card.text-center.col-lg-4.col-md-6(style = "margin: 5px 0px;")                      
            = link_to image_tag(inventory_item_category.image_url(:inventory_item)), inventory_item_category, :class => "img card-img-top"          
            .card-body       
              %h5.card-title 
                =inventory_item_category.category_name
              %p.card-text                            
                = link_to 'Details', inventory_item_category, class: 'btn button btn-primary'

app/views/inventory_item_categories/new.html.erb
<h1>New Inventory Item Category</h1>

<%= render 'form', inventory_item_category: @inventory_item_category %>

<%= link_to 'Back', inventory_item_categories_path %>

app/views/inventory_item_categories/show.html.haml
- if user_signed_in? && current_user.admin
  %p#notice= notice
  %p
    %strong Category name:
    = @inventory_item_category.category_name
  = link_to 'Edit', edit_inventory_item_category_path(@inventory_item_category)
  |
  = link_to 'Back', inventory_item_categories_path
- else
  .card(style = "margin: 20px 0px;")
    .card-header
      %strong 
        Category name:  
        = @inventory_item_category.category_name
        - @inventory_items = @inventory_item_category.inventory_items
    .card-body
      .row        

        - @inventory_items.each do |inventory_item|
          .card.text-center.col-lg-4.col-md-6(style = "margin: 5px 0px;")          
            = link_to image_tag(inventory_item.image_url(:inventory_item)), inventory_item, :class => "img card-img-top"
            .card-body       
              %h5.card-title 
                =inventory_item.name
              %p.card-text
                Unit Price:
                =number_to_currency inventory_item.price 
              = button_to 'Add to cart', order_line_items_path(inventory_item_id: inventory_item), class: 'btn button btn-primary'